# 行列積の実装

## 【問題1】行列積を手計算する
### AとBの行列積を手計算で解いてください。
### 計算過程もマークダウンテキストを用いて説明してください。

(m × n） の行列と (n × l） の行列の積は (m × l）の行列

行列A, B (m × n） の行列と (n × l） の行列の積は (m × l）の行列

A : A_ndarray = np.array([[a00, a01, a02], [a10, a11, a12], [a20, a21, a22]])

B : B_ndarray = np.array([[b00, b01, b02], [b10, b11, b12], [b20, b21, b22]])

行列積AB
AB : AB_ndarray = np.array([[AB00, AB01, AB02], [AB10, AB11, AB12], [AB20, AB21, AB22]])

AB00：Aの0行目とBの0列目の内積 

AB00 = -1* 0 + 2 * 0 + 3 * 2 = 6

AB01：Aの0行目とBの1列目の内積

AB01 = -1* 2 + 2 * 2 + 3 * 9 = 29

AB02：Aの0行目とBの2列目の内積

AB02 = -1* 1 + 2 * -8 + 3 * -1 = -20

AB10：Aの1行目とBの0列目の内積

AB10 = 4 * 0 + -5 * 0 + 6 * 2 = 12

AB11：Aの1行目とBの1列目の内積

AB11 = 4 * 2 + -5 * 2 + 6 * 9 = 52

AB12：Aの1行目とBの2列目の内積

AB12 = 4 * 1 + -5 * -8 + 6 * -1 = 38

AB20：Aの2行目とBの0列目の内積

AB20 = 7 * 0 + 8 * 0 + -9 * 2 = -18

AB21：Aの2行目とBの1列目の内積

AB21 = 7 * 2 + 8 * 2 + -9 * 9 = -51

AB22：Aの2行目とBの2列目の内積

AB22 = 7 * 1 + 8 * -8 + -9 * -1 = -48

AB_ndarray = np.array([[6, 29, -20], [12, 52, 38], [-18, -51, -48]])

In [2]:
import numpy as np
AB_ndarray = np.array([[6, 29, -20], [12, 52, 38], [-18, -51, -48]])
print(AB_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題2】NumPyの関数による計算

In [3]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(a_ndarray @ b_ndarray)
# print(np.matmul(a_ndarray, b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題3】ある要素の計算を実装

手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。


In [4]:
a_ndarray = np.array([[-1, 2, 3], 
                                        [4, -5, 6], 
                                        [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], 
                                        [0, 2, -8], 
                                        [2, 9, -1]])

# for文を用いてAB[0][0]の計算
list_1 = []
for i in range(3):
    c = a_ndarray[0][i]*b_ndarray[i][0]
    list_1.append(c)    
print(sum(list_1))

list_2 = []
for i in range(3):
    c = a_ndarray[0][i]*b_ndarray[i][1]
    list_2.append(c)    
print(sum(list_2))

list_3 = []
for i in range(3):
    c = a_ndarray[0][i]*b_ndarray[i][2]
    list_3.append(c)    
print(sum(list_3))

list_4 = []
for i in range(3):
    c = a_ndarray[1][i]*b_ndarray[i][0]
    list_4.append(c)    
print(sum(list_4))

list_5 = []
for i in range(3):
    c = a_ndarray[1][i]*b_ndarray[i][1]
    list_5.append(c)    
print(sum(list_5))

list_6 = []
for i in range(3):
    c = a_ndarray[1][i]*b_ndarray[i][2]
    list_6.append(c)    
print(sum(list_6))

list_7 = []
for i in range(3):
    c = a_ndarray[2][i]*b_ndarray[i][0]
    list_7.append(c)    
print(sum(list_7))

list_8 = []
for i in range(3):
    c = a_ndarray[2][i]*b_ndarray[i][1]
    list_8.append(c)    
print(sum(list_8))

list_9 = []
for i in range(3):
    c = a_ndarray[2][i]*b_ndarray[i][2]
    list_9.append(c)    
print(sum(list_9))

p = np.array([[sum(list_1), sum(list_2), sum(list_3)],[sum(list_4), sum(list_5), sum(list_6)], [sum(list_7), sum(list_8), sum(list_9)]])
print(p)

6
29
-20
12
52
38
-18
-51
-48
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [5]:
# 手計算でABの各要素計算
cal_1 = a_ndarray[0][0]*b_ndarray[0][0]+a_ndarray[0][1]*b_ndarray[1][0]+a_ndarray[0][2]*b_ndarray[2][0]
cal_2 = a_ndarray[0][0]*b_ndarray[0][1]+a_ndarray[0][1]*b_ndarray[1][1]+a_ndarray[0][2]*b_ndarray[2][1]
cal_3 = a_ndarray[0][0]*b_ndarray[0][2]+a_ndarray[0][1]*b_ndarray[1][2]+a_ndarray[0][2]*b_ndarray[2][2]

cal_4 = a_ndarray[1][0]*b_ndarray[0][0]+a_ndarray[1][1]*b_ndarray[1][0]+a_ndarray[1][2]*b_ndarray[2][0]
cal_5 = a_ndarray[1][0]*b_ndarray[0][1]+a_ndarray[1][1]*b_ndarray[1][1]+a_ndarray[1][2]*b_ndarray[2][1]
cal_6 = a_ndarray[1][0]*b_ndarray[0][2]+a_ndarray[1][1]*b_ndarray[1][2]+a_ndarray[1][2]*b_ndarray[2][2]

cal_7 = a_ndarray[2][0]*b_ndarray[0][0]+a_ndarray[2][1]*b_ndarray[1][0]+a_ndarray[2][2]*b_ndarray[2][0]
cal_8 = a_ndarray[2][0]*b_ndarray[0][1]+a_ndarray[2][1]*b_ndarray[1][1]+a_ndarray[2][2]*b_ndarray[2][1]
cal_9 = a_ndarray[2][0]*b_ndarray[0][2]+a_ndarray[2][1]*b_ndarray[1][2]+a_ndarray[2][2]*b_ndarray[2][2]

print(cal_1)
print(cal_2)
print(cal_3)
print(cal_4)
print(cal_5)
print(cal_6) 
print(cal_7)
print(cal_8)
print(cal_9)

6
29
-20
12
52
38
-18
-51
-48


In [6]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], 
                                        [4, -5, 6], 
                                        [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], 
                                        [0, 2, -8], 
                                        [2, 9, -1]])
# c = np.zeros((3,3),dtype=int).tolist() # 
c = [[0]*3 for _ in range(3)] # [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for z in range(3):
    for j in range(3):
        for i in range(3):
            c[z][j] = a_ndarray[z][i]*b_ndarray[i][j]+c[z][j]
        C = c[z][j]
print(C)

-48


In [7]:
m = []
for i in range(3):
    for h in range(3):
        for g in range(3):
            m.append([i, h ,g])
print(m)

[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 1, 0], [0, 1, 1], [0, 1, 2], [0, 2, 0], [0, 2, 1], [0, 2, 2], [1, 0, 0], [1, 0, 1], [1, 0, 2], [1, 1, 0], [1, 1, 1], [1, 1, 2], [1, 2, 0], [1, 2, 1], [1, 2, 2], [2, 0, 0], [2, 0, 1], [2, 0, 2], [2, 1, 0], [2, 1, 1], [2, 1, 2], [2, 2, 0], [2, 2, 1], [2, 2, 2]]


In [8]:
m = []
for i in range(3):
    for h in range(3):
        m.append([i, h])
print(m)

[[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2]]


## 【問題4】行列積を行う関数の作成

#### 問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。
#### 行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

#### 計算結果である 
#### 3×3の行列Cの各要素 ci,j は数式で表すと次のようになります。
#### for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックスiやjを1増やすと、次の行や列に移ることができます。

In [19]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])


def gyouretu(a_ndarray, b_ndarray):
# for文を用いてAB[0][0]の計算
        
    list_1 = []
    for i in range(3):
        c = a_ndarray[0][i]*b_ndarray[i][0]
        list_1.append(c) 

    list_2 = []
    for i in range(3):
        c = a_ndarray[0][i]*b_ndarray[i][1]
        list_2.append(c)    

    list_3 = []
    for i in range(3):
        c = a_ndarray[0][i]*b_ndarray[i][2]
        list_3.append(c)    

    list_4 = []
    for i in range(3):
        c = a_ndarray[1][i]*b_ndarray[i][0]
        list_4.append(c)    

    list_5 = []
    for i in range(3):
        c = a_ndarray[1][i]*b_ndarray[i][1]
        list_5.append(c)    

    list_6 = []
    for i in range(3):
        c = a_ndarray[1][i]*b_ndarray[i][2]
        list_6.append(c)    

    list_7 = []
    for i in range(3):
        c = a_ndarray[2][i]*b_ndarray[i][0]
        list_7.append(c)    

    list_8 = []
    for i in range(3):
        c  = a_ndarray[2][i]*b_ndarray[i][1]
        list_8.append(c)    
         
    list_9 = []
    for i in range(3):
        c = a_ndarray[2][i]*b_ndarray[i][2]
        list_9.append(c)    

    p = np.array([[sum(list_1), sum(list_2), sum(list_3)],[sum(list_4), sum(list_5), sum(list_6)], [sum(list_7), sum(list_8), sum(list_9)]])
    return p

gyouretu(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【問題5】計算が定義されない入力を判定する

In [ ]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9], [4, -5, 6]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
length = len(a_ndarray)

def gyouretu(a_ndarray, b_ndarray):
# for文を用いてAB[0][0]の計算
    if len(a_ndarray) == 3:
        
        list_1 = []
        for i in range(3):
            c = a_ndarray[0][i]*b_ndarray[i][0]

        list_2 = []
        for i in range(3):
            c = a_ndarray[0][i]*b_ndarray[i][1]
            list_2.append(c)    

        list_3 = []
        for i in range(3):
            c = a_ndarray[0][i]*b_ndarray[i][2]
            list_3.append(c)    

        list_4 = []
        for i in range(3):
            c = a_ndarray[1][i]*b_ndarray[i][0]
            list_4.append(c)    

        list_5 = []
        for i in range(3):
            c = a_ndarray[1][i]*b_ndarray[i][1]
            list_5.append(c)    

        list_6 = []
        for i in range(3):
            c = a_ndarray[1][i]*b_ndarray[i][2]
            list_6.append(c)    

        list_7 = []
        for i in range(3):
            c = a_ndarray[2][i]*b_ndarray[i][0]
            list_7.append(c)    

        list_8 = []
        for i in range(3):
            c = a_ndarray[2][i]*b_ndarray[i][1]
            list_8.append(c)    

        list_9 = []
        for i in range(3):
            c = a_ndarray[2][i]*b_ndarray[i][2]
            list_9.append(c)    
            
        p = np.array([[sum(list_1), sum(list_2), sum(list_3)],[sum(list_4), sum(list_5), sum(list_6)], [sum(list_7), sum(list_8), sum(list_9)]])
    
        return p

    else:
        print("計算できない")

gyouretu(a_ndarray, b_ndarray)

## 【問題6】転置

#### 片方の行列を転置することで、行列積が計算できるようになります。
#### np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [93]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])


e_ndarray_T = e_ndarray.T
print(e_ndarray)
print(e_ndarray_T)

print(d_ndarray @ e_ndarray_T)

[[-9  8  7]
 [ 6 -5  4]]
[[-9  6]
 [ 8 -5]
 [ 7  4]]
[[ 46  -4]
 [-34  73]]
