**【問題1】これまで利用してきたクラスの列挙**

Pandas<br>
<class 'pandas.core.frame.DataFrame'><br>

matplotlib<br>
<class 'matplotlib.text.Text'><br>

scikit-learn<br>
<class 'sklearn.neighbors._classification.KNeighborsClassifier'>

**【問題2】これまで利用してきたメソッドやインスタンス変数の列挙**

メソッド<br>
discribe(), head(), reshape(), np.arrange(), range()

インスタンス変数<br>
転値.T, np.random.seed(0), .values , .iloc , .loc

**【問題3】標準化クラスをスクラッチで作成**

In [1]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [2]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """ 
     
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        # 平均　np.mean()
        self.mean_ = np.mean(X, axis=0)
        # 分散 np.var()
        self.var_ = np.var(X, axis=0)

        pass
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        # 標準化された特徴量　= （X - 平均）　/ 標準偏差
        X_scaled = (X - self.mean_) / self.var_**1/2
        pass
        return X_scaled



In [3]:
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[  1.57068063   1.11896349  -2.38095238  -1.78571429]
 [  0.2617801   -1.82567727  -2.38095238  -1.78571429]
 [ -1.04712042  -0.64782097  -7.14285714  -1.78571429]
 [ -1.70157068  -1.23674912   2.38095238  -1.78571429]
 [  0.91623037   1.70789164  -2.38095238  -1.78571429]
 [  3.53403141   3.47467609  11.9047619   16.07142857]
 [ -1.70157068   0.53003534  -2.38095238   7.14285714]
 [  0.91623037   0.53003534   2.38095238  -1.78571429]
 [ -3.0104712   -2.41460542  -2.38095238  -1.78571429]
 [  0.2617801   -1.23674912   2.38095238 -10.71428571]]


**【問題4】 四則演算を行うクラスの作成**<br>
引き算、掛け算、割り算のメソッドを加える。<br>
コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出す。<br>

In [5]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        print(value)
        if str(value).isdigit()==True:
            self.value = value
            print("初期値{}が設定されました".format(self.value))
        else:
            print("Input value is not valid number.")
    
    # 足し算（）
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
        
    # 引き算（subtraction）
    def subtraction(self, value3):
        """
        受け取った引数をself.valueから引く
        """
        self.value -= value3
        
    # 掛け算（multiplication）
    def multiplication(self, value4):
        """
        受け取った引数をself.valueに掛ける
        """
        self.value *= value4
        
    # 割り算（division）
    def division(self, value5):
        """
        受け取った引数でself.valueを割る
        """
        self.value /= value5
        
    
example = ExampleClass(7)
print("value : {}".format(example.value))

# example.add(8)
# print("value : {}".format(example.value))

# example.division(5)
# print("value : {}".format(example.value))


7
初期値7が設定されました
value : 7
