## **【問題1】train_test_split のスクラッチ**

In [124]:
import numpy as np
from sklearn.model_selection import train_test_split
import random

In [125]:
def scratch_train_test_split(X, y, train_size=0.8):
    """検証データを分割する。
    Parameters
    ----------
    X : ndarray
      訓練データ (n_samples, n_features)
    y : ndarray
      正解値 (n_samples,)
    train_size : float
      何割をtrainとするか指定 (0 < train_size < 1)
    Returns
    -------
    X_train : ndarray
      訓練データ (n_samples, n_features)
    X_test : ndarray
      検証データ (n_samples, n_features)
    y_train : ndarray
      訓練データの正解値 (n_samples,)
    y_test : ndarray
      検証データの正解値 (n_samples,)
    """
    
    arr_rand = np.random.choice(range(X.shape[0]), int(train_size*X.shape[0]))
    split = arr_rand < np.percentile(arr_rand, train_size/10)
    # train_size ×　Xのlen(行) = yのlen(行)をfloatからint型へ変換
    split_point = int(train_size *len(X))
    
    # Xの0行目からsplit_point行目まで抽出
    X_train = X[0:split_point]
    # Xのsplit_point行目から最後の行まで抽出
    X_test = X[split_point:]
    
    # yの0行目からsplit_point行目まで抽出
    y_train= y[0:split_point]
    # yのsplit_point行目から最後の行まで抽出
    y_test= y[split_point:]
    
    pass
    return X_train, X_test, y_train, y_test

x_practice_array = np.arange(100).reshape(50, 2)
y_practice_array = np.arange(50,)
train_size=0.8

# scratch_train_test_split(x_practice_array, y_practice_array, train_size=train_size)

In [126]:
x_practice_array = np.arange(100).reshape(50, 2)
y_practice_array = np.arange(50,)

X_train, X_test, y_train, y_test = train_test_split(x_practice_array, y_practice_array,train_size=0.8)
type(X_train)

numpy.ndarray

## **【問題2】 分類問題を解くコードの作成**

In [127]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [225]:
# irisデータセット0


# irisデータセットをirisに格納
iris = load_iris()
iris_dataset = load_iris()
# print(iris_dataset.keys()) 
# dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

# irisデータセットをDataFrameに変換
# df = pd.DataFrame(iris.data, columns=iris.feature_names)
X = pd.DataFrame(iris.data, columns=iris.feature_names)
# iris_target = pd.DataFrame(iris.target, columns =['Species'])
y = pd.DataFrame(iris.target, columns =['Species'])
df = pd.concat([X, y], axis=1)

# iris_target setosa = 0, versicolor = 1, virginica = 2
# virgicolorとvirginicaを抽出
df_select = df.query('Species == [1, 2]')
df_select

x_0 = df_select.iloc[:, 0:4]
y_0 = df_select.iloc[:, 4]

In [159]:
# シンプルデータセット1


import numpy as np
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]
f0 = np.random.multivariate_normal(f0, cov, n_samples // 2)
f1 = np.random.multivariate_normal(f1, cov, n_samples // 2)
x_1 = np.concatenate([f0, f1])
y_1 = np.concatenate([
    np.full(n_samples // 2, 1),
    np.full(n_samples // 2, -1)
])

In [226]:
# シンプルデータセット2


x_2 = np.array([
    [-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
    [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
    [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
    [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
    [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
    [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
    [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
    [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
    [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
    [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
    [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
    [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
    [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
    [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
    [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
    [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
    [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
    [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
    [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
    [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ],
])
y_2 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [227]:
# データ分割

# 自作の関数で検証データ分割
import random
# ⓪
# irisデータ 説明変数x_0, 目的変数y_0
x_0_shuffle = x_0.sample(frac=1)
y_0_shuffle = y_0.sample(frac=1)
x_0_train, x_0_test, y_0_train, y_0_test = scratch_train_test_split(x_0_shuffle, y_0_shuffle, train_size=0.8)

# ①
# シンプルデータセット1作成コード 説明変数x_1, 目的変数y_1
np.random.shuffle(x_1)
np.random.shuffle(y_1)
x_1_train, x_1_test, y_1_train, y_1_test = scratch_train_test_split(x_1, y_1, train_size=0.8)

# ②
# シンプルデータセット2作成コード 説明変数x_2, 目的変数y_2
np.random.shuffle(x_2)
np.random.shuffle(y_2)
x_2_train, x_2_test, y_2_train, y_2_test = scratch_train_test_split(x_2, y_2, train_size=0.8)

In [228]:
# 推定する関数


def scl_predict(x_train, x_test, y_train, y_test):   
    # インスタンスを作成
    scl = StandardScaler()
    #学習用データで標準化
    scl.fit(x_train) 
    x_train_transformed = scl.transform(x_train)
    x_test_transformed = scl.transform(x_test)


    # 勾配降下法を用いて計算する SGDClassifierを使用。
    # 引数で 誤差関数　loss="log"　に設定することでロジスティック回帰の計算が可能。

    #インスタンスを作成
    sgd = SGDClassifier(loss='log')
    Linsvc = LinearSVC()
    clf = DecisionTreeClassifier()
    
    # 学習
    sgd.fit(x_train_transformed, y_train)
    Linsvc.fit(x_train_transformed, y_train)
    clf.fit(x_train_transformed, y_train)
    
    # 推定
    y_sgd_pred = sgd.predict(x_test_transformed)
    y_Linsvc_pred = Linsvc.predict(x_test_transformed)
    y_clf_pred = clf.predict(x_test_transformed)
    
    return y_sgd_pred, y_Linsvc_pred, y_clf_pred

y_sgd_pred, y_Linsvc_pred, y_clf_pred = scl_predict(x_0_train, x_0_test, y_0_train, y_0_test)
print("irisデータセット0")
print('ロジスティック回帰:\n{}\nSVM:\n{}\n決定木:\n{}'.format(y_sgd_pred, y_Linsvc_pred, y_clf_pred))

y_sgd_pred, y_Linsvc_pred, y_clf_pred = scl_predict(x_1_train, x_1_test, y_1_train, y_1_test)
print("")
print("シンプルデータセット1")
print('ロジスティック回帰:\n{}\nSVM:\n{}\n決定木:\n{}'.format(y_sgd_pred, y_Linsvc_pred, y_clf_pred))

y_sgd_pred, y_Linsvc_pred, y_clf_pred = scl_predict(x_2_train, x_2_test, y_2_train, y_2_test)
print("")
print("シンプルデータセット2")
print('ロジスティック回帰:\n{}\nSVM:\n{}\n決定木:\n{}'.format(y_sgd_pred, y_Linsvc_pred, y_clf_pred))

irisデータセット0
ロジスティック回帰:
[2 2 2 1 1 1 2 2 2 1 1 1 1 1 1 1 1 2 2 2]
SVM:
[2 2 2 1 2 2 2 2 2 1 1 1 1 1 1 1 1 2 2 2]
決定木:
[2 1 1 1 2 2 1 1 2 2 1 1 1 1 2 1 1 2 2 1]

シンプルデータセット1
ロジスティック回帰:
[-1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1]
SVM:
[-1  1 -1  1  1  1  1  1  1  1  1  1 -1  1  1 -1  1  1  1  1  1 -1  1  1
  1  1  1 -1  1  1  1  1  1  1  1  1 -1 -1  1 -1  1 -1  1  1  1  1 -1  1
  1  1 -1  1  1  1  1  1 -1  1  1  1  1  1 -1  1 -1  1  1  1  1  1  1  1
 -1  1  1 -1  1 -1  1 -1  1  1  1 -1  1  1  1  1 -1  1  1  1  1  1  1 -1
  1  1  1  1]
決定木:
[-1 -1 -1 -1 -1  1 -1  1  1  1 -1  1 -1  1 -1 -1 -1 -1 -1  1  1 -1  1 -1
 -1  1 -1  1  1  1  1  1 -1 -1 -1  1  1  1 -1 -1 -1  1  1  1 -1  1 -1  1
 -1  1  1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1  1 -1 

### ロジスティック回帰 

In [230]:
# from sklearn.linear_model import SGDClassifier
# from sklearn.preprocessing import StandardScaler
# from sklearn.metrics import r2_score
# from sklearn.metrics import accuracy_score

# # インスタンスを作成
# scl = StandardScaler()
# #学習用データで標準化
# scl.fit(x_0_train) 
# x_0_train_transformed = scl.transform(x_0_train)
# x_0_test_transformed = scl.transform(x_0_test)


# # 勾配降下法を用いて計算する SGDClassifierを使用。
# # 引数で 誤差関数　loss="log"　に設定することでロジスティック回帰の計算が可能。

# # モデルのインスタンスを作成
# sgd = SGDClassifier(loss='log')

# # fit 学習
# sgd.fit(x_0_train_transformed, y_0_train)

# # predict 予測
# y_0_sgd_pred = sgd.predict(x_0_test_transformed)

###　SVM

In [193]:
# from sklearn.svm import LinearSVC

# # インスタンスを作成
# scl = StandardScaler()
# #学習用データで標準化
# scl.fit(x_1_train) 
# x_1_train_transformed = scl.transform(x_1_train)
# x_1_test_transformed = scl.transform(x_1_test)

# #LinearSVMのインスタンスを作成
# Linsvc = LinearSVC()

# #LinearSVMでデータを学習
# Linsvc.fit(x_1_train_transformed, y_1_train)

# #LinearSVMでアヤメの種類を予測
# y_1_Linsvc_pred = Linsvc.predict(x_1_test_transformed)

### 決定木

In [196]:
# from sklearn.tree import DecisionTreeClassifier

# # インスタンスを作成
# scl = StandardScaler()
# #学習用データで標準化
# scl.fit(x_2_train) 
# x_2_train_transformed = scl.transform(x_2_train)
# x_2_test_transformed = scl.transform(x_2_test)

# #　DecisionTreeのインスタンスを作成
# clf = DecisionTreeClassifier()

# #　DecisionTreeでデータを学習
# clf.fit(x_2_train_transformed, y_2_train)

# #LinearSVMでアヤメの種類を予測
# y_2_clf_pred = clf.predict(x_2_test_transformed)

## 【問題3】回帰問題

In [278]:
import pandas as pd
import numpy as np
from sklearn.linear_model import SGDRegressor

# House Pricesコンペティションのデータセット
train = pd.read_csv('train.csv')

# Xに説明変数GrLivArea(リビングの広さ)とYearBuiltを抽出
X_df = train[["GrLivArea", "YearBuilt"]]

# Yに目的変数SalePriceを抽出
Y_df = train[["SalePrice"]]

# X_df, Y_dfをconcatメソッドで　axis=1に結合
df = pd.concat([X_df, Y_df], axis=1)
pd.set_option('display.max_rows', None)

In [279]:
x_train, x_test, y_train, y_test = train_test_split(X_df, Y_df,train_size=0.8)

# # インスタンスを作成
# scl = StandardScaler()
# #学習用データで標準化
# scl.fit(x_train) 
# x_train_transformed = scl.transform(x_train)
# x_test_transformed = scl.transform(x_test)

# インスタンスを作成
sgdr = SGDRegressor()
# y_trainをnumpy.ravel()関数で平坦化
sgdr.fit(x_train, np.ravel(y_train))

# predict 予測
y_sgdr_pred = sgdr.predict(x_test)
y_sgdr_pred

array([2.32471286e+15, 2.51298732e+15, 2.44004793e+15, 2.33851690e+15,
       2.95164687e+15, 1.99558722e+15, 2.67580036e+15, 2.53148926e+15,
       2.25265718e+15, 2.45336771e+15, 2.42871271e+15, 2.61750869e+15,
       2.29840776e+15, 2.46354975e+15, 2.31272855e+15, 2.50967481e+15,
       2.28648090e+15, 2.45649794e+15, 2.25499364e+15, 2.67763000e+15,
       2.33028694e+15, 2.27685802e+15, 2.12427695e+15, 2.48963529e+15,
       2.32594847e+15, 3.17607639e+15, 2.35110791e+15, 2.49872638e+15,
       2.42348301e+15, 2.61481279e+15, 2.60326794e+15, 2.53660644e+15,
       1.98161834e+15, 2.15631583e+15, 2.10930467e+15, 2.37104757e+15,
       2.64354670e+15, 2.38725306e+15, 2.89243424e+15, 2.52614739e+15,
       3.25176161e+15, 2.65781755e+15, 2.39383805e+15, 2.66112767e+15,
       2.61083889e+15, 2.16035472e+15, 2.60983036e+15, 2.03638033e+15,
       2.45207465e+15, 2.36859380e+15, 2.11163362e+15, 2.53772235e+15,
       1.93165171e+15, 2.36450498e+15, 2.40145893e+15, 2.50118015e+15,
      